const VENEZUELAN_BANKS = [
  { code: "0191", name: "Banco Nacional de Credito" },
  { code: "0102", name: "Banco de Venezuela" },
  { code: "0104", name: "Venezolano de Credito" },
  { code: "0105", name: "Banco Mercantil" },
  { code: "0108", name: "Banco Provincial" },
  { code: "0114", name: "Bancaribe" },
  { code: "0115", name: "Banco Exterior" },
  { code: "0116", name: "Banco Occidental de Descuento" },
  { code: "0128", name: "Banco Caroni" },
  { code: "0134", name: "Banesco" },
  { code: "0137", name: "Banco Sofitasa" },
  { code: "0138", name: "Banco Plaza" },
  { code: "0146", name: "Bangente" },
  { code: "0151", name: "BFC Banco Fondo Comun" },
  { code: "0156", name: "100% Banco" },
  { code: "0157", name: "Banco del Sur" },
  { code: "0163", name: "Banco del Tesoro" },
  { code: "0166", name: "Banco Agricola de Venezuela" },
  { code: "0168", name: "Bancrecer" },
  { code: "0169", name: "Mi Banco" },
  { code: "0171", name: "Banco Activo" },
  { code: "0172", name: "Bancamiga" },
  { code: "0174", name: "Banplus" },
  { code: "0175", name: "Banco Bicentenario" },
  { code: "0177", name: "Banco de la Fuerza Armada Nacional" },
];

export default VENEZUELAN_BANKS;